name: betaBuild

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      # Setup Enviroment
      - uses: actions/checkout@v1
      - name: Generate Version Code
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export VC=$(curl https://api.github.com/repos/kagonlineteam/kag-app/releases -H "Authorization: Bearer $GH_TOKEN" | grep -c '"author": {')
          sed -i.bak -e 's/. #VC/'"$VC"'/' pubspec.yaml
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      # Build a signed Android AAB and APK
      - id: android-key
        name: Extract Android key file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'key.jks'
          encodedString: ${{ secrets.KEY_JKS }}
      - name: build android
        run: cp $KEY_LOCATION android/key.jks && flutter build apk --release
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_LOCATION: ${{ steps.android-key.outputs.filePath }}
      # Add the built APK to Action
      - uses: actions/upload-artifact@v1
        with:
          name: android-release-apk
          path: build/app/outputs/apk/release/app-release.apk
  build-and-release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: install flutter dependenccies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Build artifacts
        run: flutter build linux --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: kag-linux.zip
          directory: build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v1
        with:
          name: kag-linux
          path: build/linux/x64/release/bundle/kag-linux.zip