name: deployStores

on:
  push:
    branches:
      - master
  release:
    types:
       - created

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    # Setup Enviroment
    - uses: actions/checkout@v1
    - name: Generate Version Code
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        export VC=$(curl https://api.github.com/repos/kagonlineteam/kag-app/releases -H "Authorization: Bearer $GH_TOKEN" | grep -c '"author": {')
        sed -i.bak -e 's/. #VC/'"$VC"'/' pubspec.yaml
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    # Build a signed Android AAB and APK
    - id: android-key
      name: Extract Android key file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'key.jks'
        encodedString: ${{ secrets.KEY_JKS }}
    - name: build android
      run: cp $KEY_LOCATION android/key.jks && flutter build apk --release && flutter build appbundle --release
      env:
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_LOCATION: ${{ steps.android-key.outputs.filePath }}
    # Add the built APK to Action
    - uses: actions/upload-artifact@v1
      with:
        name: android-release-apk
        path: build/app/outputs/apk/release/app-release.apk
    # Deploy Android via Fastlane
    - id: google-key
      name: Extract Google key file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'googleaccount.json'
        encodedString: ${{ secrets.GOOGLE_ACCOUNT }}
    - name: copy fastlane files
      run: cp $GOOGLE_LOCATION android/googleaccount.json
      env:
        GOOGLE_LOCATION: ${{ steps.google-key.outputs.filePath }}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.2'
    - uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'beta'
        subdirectory: 'android'
  ios:
    runs-on: macOS-latest

    steps:
      # Setup Enviroment
      - uses: actions/checkout@v1
      - name: Generate Version Code
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export VC=$(curl https://api.github.com/repos/kagonlineteam/kag-app/releases -H "Authorization: Bearer $GH_TOKEN" | grep -c '"author": {')
          sed -i.bak -e 's/. #VC/'"$VC"'/' pubspec.yaml
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'beta'
      - run: flutter pub get
      # Build
      - run: flutter build ios --no-codesign
      # Get SSH Key used for Match Repo
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.FASTLANE_MATCH_SSH }}
            known_hosts: ${{ secrets.GH_SSH_KNOWN_HOST }}
      # Deploy with Fastlane
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 2.7.2
            bundler-cache: true
      - uses: maierj/fastlane-action@v1.4.0
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            FASTLANE_USER: ${{ secrets.APPLE_ACCOUNT }}
            FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        with:
          lane: 'beta'
          subdirectory: 'ios'
