name: main

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'beta'
    - run: flutter pub get
    - name: build-android
      run: echo $KEY_JKS > key.jks && flutter build apk --release && flutter build appbundle --release
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk 
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/bundle/release/app-release.aab
