name: testDeploy

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Setup Enviroment
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      # Build web Data
      - name: build-web
        run: flutter config --enable-web && flutter build web
      - name: generate random id to not load old cach
        run: sed -i.bak -e "s/main.dart.js/main.dart.js?version=$RANDOM/g" build/web/index.html
      # Deploy Web by Copying the Files to Production
      - name: deploy web
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -ar --delete
          path: build/web/*
          remote_path: /var/www/app/test/${{github.event.number}}/
          remote_host: ${{ secrets.SSH_URL }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
